"""empty message

Revision ID: 106d1f818041
Revises: bbf3daf3b5d0
Create Date: 2020-03-14 06:46:03.517745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106d1f818041'
down_revision = 'bbf3daf3b5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politician', sa.Column('cover_image', sa.String(length=100), nullable=True))
    op.drop_column('politician', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politician', sa.Column('avatar_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('politician', 'cover_image')
    # ### end Alembic commands ###
