"""empty message

Revision ID: 3168769e5656
Revises: 6c3ae0d91c0f
Create Date: 2020-03-14 06:07:28.497453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3168769e5656'
down_revision = '6c3ae0d91c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politician', sa.Column('politician_avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politician', 'politician_avatar')
    # ### end Alembic commands ###
